_wandb:
    value:
        cli_version: 0.25.0
        e:
            gebh1w62s9eeapdbmffdzf1zq9dt99ik:
                apple: {}
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "494384795648"
                        used: "204765609984"
                email: mayank.chandak21@gmail.com
                executable: /Users/mayankchandak/Desktop/MY STUFF/Courses/SEM8/Intro to DL/Assignments/da6401/bin/python
                git:
                    commit: e52c752c0ca946ff07b7acf6fc016f53be190d5d
                    remote: https://github.com/mnm-21/ME22B224_DA6401_Assignment_1.git
                host: Mayanks-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/mayankchandak/Desktop/MY STUFF/Courses/SEM8/Intro to DL/Assignments/da6401_assignment_1/src/train.py
                python: CPython 3.10.15
                root: /Users/mayankchandak/Desktop/MY STUFF/Courses/SEM8/Intro to DL/Assignments/da6401_assignment_1
                startedAt: "2026-03-08T06:57:59.359659Z"
                writerId: gebh1w62s9eeapdbmffdzf1zq9dt99ik
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.10.15
            "5": 0.25.0
            "12": 0.25.0
            "13": darwin-arm64
activation:
    value: sigmoid
batch_size:
    value: 32
dataset:
    value: mnist
detailed_log:
    value: false
epochs:
    value: 10
hidden_size:
    value:
        - 128
        - 64
learning_rate:
    value: 0.076
loss:
    value: cross_entropy
model_save_path:
    value: best_model.npy
num_layers:
    value: 2
optimizer:
    value: momentum
wandb_project:
    value: da6401_assignment_1
weight_decay:
    value: 0
weight_init:
    value: xavier
